env=dev

#Stato fornitore
statoFornitore.bozza=B
statoFornitore.invitato=I
statoFornitore.Registrato=R

#Stato Allegato
statoAllegato.bozza=B
statoAllegato.inserito=I
statoAllegato.valutazione=V
statoAllegato.rigettato=R
statoAllegato.approvato=A
statoAllegato.visionato=MV

#Macro tipologia
macroTipologia.aziendali=AZ
macroTipologia.personali=PE

#Tipologia
tipologia.moduli=MOD