env=dev

#Stato fornitore
statoFornitore.bozza=B
statoFornitore.invitato=I
statoFornitore.Registrato=R

#Stato Allegato
statoAllegato.bozza=B
statoAllegato.inserito=I
statoAllegato.valutazione=V
statoAllegato.rigettato=R
statoAllegato.approvato=A