env=dev

#Stato fornitore
statoFornitore.bozza=B
statoFornitore.invitato=I
statoFornitore.Registrato=R

#Stato Allegato
statoAllegato.bozza=B
statoAllegato.inserito=I
statoAllegato.valutazione=V
statoAllegato.rigettato=R
statoAllegato.approvato=A
statoAllegato.visionato=MV
statoAllegato.annullato=X
statoAllegato.inScadenza=IS
statoAllegato.scaduto=S

#Macro tipologia
macroTipologia.aziendali=AZ
macroTipologia.personali=PE

#Tipologia
tipologia.moduli=MOD

#Codici messaggi
msg.invitoUtentiInterni=RUI
msg.resetPassword=RP
msg.mfa=MFA
msg.invitoUtentiFornitori=RUF
msg.docInScadenza=DIS
msg.docDaInserire=DDI